require_relative "./homebrew-utils/github_download_strategy.rb" 
# This file is generated by the release script, do not change it directly.
class Yak < Formula
  desc "Get aws credentials from vault"
  homepage "https://github.com/eventbrite/vault-aws-iam-authenticator"
  url "https://api.github.com/repos/eventbrite/vault-aws-iam-authenticator/releases/assets/18403098", :using => CustomGitHubPrivateRepositoryReleaseDownloadStrategy
  sha256 "ffc4ced31a192363b04a13efd27b42f85c8bd7d541c69cbc85a81e77ff079cab"
  version "0.0.7"

  def install
    bin.install "vault-aws-iam-authenticator"
  end
end
