require_relative "./homebrew-utils/github_download_strategy.rb" 
# This file is generated by the release script, do not change it directly.
class Yak < Formula
  desc "A command line tool to manage dev environments on Kubernetes"
  homepage "https://github.com/eventbrite/yak"
  url "https://api.github.com/repos/eventbrite/yak/releases/assets/18439820", :using => CustomGitHubPrivateRepositoryReleaseDownloadStrategy
  sha256 "014e6315655c3be5eadcaca06142fcbd5396c37d6c84c213d11465beae3b2cc4"
  version "0.2.1"
  bottle :unneeded
  depends_on "kubernetes-cli"
  depends_on "watch"
  depends_on "vault-aws-iam-authenticator"

  resource "aws-iam-authenticator" do
    url "https://amazon-eks.s3-us-west-2.amazonaws.com/1.11.5/2018-12-06/bin/darwin/amd64/aws-iam-authenticator"
    sha256 "ef60d7ea5108b4de19f7fe59514643a7665df6832f94be620405138d8f60dd18"
  end

  def install
    bin.install "yak"
    resource("aws-iam-authenticator").stage { bin.install "aws-iam-authenticator" }
  end
end
