version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    working_directory: /go/src/github.com/eb-rubenespinosa/go-tests
    steps:
    - checkout
    - run: go get -u github.com/golang/dep/cmd/dep
    - run:
        name: run build
        command: |
          dep ensure
          go build -v
    - run:
        name: run tests
        command: |
          go fmt ./...
          go vet ./...
          go test -v ./...
  publish-github-release:
    docker:
      - image: circleci/golang:1.9
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            VERSION=$(my-binary --version)
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/
workflows:
  version: 2
  build_test_and_release:
    jobs:
      - build
      - publish-github-release:
          requires:
            - build
