on: 
  release:
    types:
      - created

name: Build and Release
jobs:
  build:
    name: Build
    strategy:
      matrix:
        go-version: [1.11.x]
        platform: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      if: success()
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Setup env
      run: |
        echo "::set-env name=GOPATH::$(go env GOPATH)"
        echo "::set-env name=GOBIN::$(go env GOPATH)/bin"
        echo "::add-path::$(go env GOPATH)/bin"
      shell: bash
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create go path
      run: |
        mkdir -p $GOPATH/pkg
        mkdir -p $GOBIN
        mkdir -p $GOPATH/src/github.com/$GITHUB_REPOSITORY
        mv ./* $GOPATH/src/github.com/$GITHUB_REPOSITORY
        rm -rf .git*
    - name: Make build
      working-directory: ${{env.GOPATH}}/src/github.com/${{env.GITHUB_REPOSITORY}}
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure  
        fi
        go build
    - name: Upload Artifacts
      working-directory: ${{env.GOPATH}}/src/github.com/${{env.GITHUB_REPOSITORY}}
      run: |
        tar czf tmp.tar.gz go-tests
        if [ "${{ matrix.platform }}" == "macos-latest" ]; then
          export PLATFORM="darwin-amd64"  
        elif [ "${{ matrix.platform }}" == "ubuntu-latest"  ]; then
          export PLATFORM="linux-amd64"  
        fi
        asset_url=$(curl \
          -X POST \
          --data-binary @tmp.tar.gz \
          -H 'Content-Type: multipart/form-data' \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }}/assets?name=yak-$PLATFORM-${{ github.event.release.tag_name }}.tar.gz" | jq -r '.id')
          echo $asset_url > ${{github.workspace}}/${{ matrix.platform }}.txt
          ls ${{github.workspace}}
    - name: Upload math result for job 2
      uses: actions/upload-artifact@v1
      with:
        name: assets
        path: ${{ matrix.platform }}.txt
  publish:
    name: Publish files in master
    needs: [build]
    runs-on: [macos-latest]
    steps:
    - name: Download math result for job 2
      uses: actions/download-artifact@v1
      with:
        name: assets
    - name: Modify brew and changelog
      run: |
        ls assets
        export LINUX_ASSET_ID=`cat assets/ubuntu-latest.txt`
        export MAC_ASSET_ID=`cat assets/macos-latest.txt`
        git init
        git pull https://${{github.actor}}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        git remote add origin https://${{github.actor}}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
        chmod +x release.sh
        ./release.sh
        
        git add yak.rb CHANGELOG.md README.md
        git commit -m "Release $VERSION"
        git status
        echo "Pushing version $VERSION to $RELEASE_BRANCH branch"
        git push --set-upstream origin master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERSION: ${{ github.event.release.tag_name }}
        CHANGELOG: ${{ github.event.release.body }}
