on:
  pull_request:
    branches:
      - "*"

name: test and build
jobs:
  test:
    name: Test
    strategy:
      matrix:
        go-version: [1.11.x]
        platform: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      if: success()
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Run tests
      run: go test -v -covermode=count

  build:
    name: Build
    strategy:
      matrix:
        go-version: [1.11.x]
        platform: [macos-latest, ubuntu-latest]
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.11
      uses: actions/setup-go@v1
      with:
        go-version: 1.11.x
      id: go
    - name: Check out code
      uses: actions/checkout@v2

    - name: Get dependencies and Build
      run: |
        export GOPATH=$HOME/go
        export GOBIN=$(go env GOPATH)/bin
        export PATH=$PATH:$GOPATH
        export PATH=$PATH:$GOBIN
        mkdir -p $GOPATH/pkg
        mkdir -p $GOBIN
        mkdir -p $GOPATH/src/github.com/$GITHUB_REPOSITORY
        mv ./* $GOPATH/src/github.com/$GITHUB_REPOSITORY
        cd $GOPATH/src/github.com/$GITHUB_REPOSITORY
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
        cd $GOPATH/src/github.com/$GITHUB_REPOSITORY && go build -v .
