on:
  pull_request:
    branches:
      - master

name: Test and build
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: PING - Dispatch initiating repository event
        run: |
          curl -H "Accept: application/vnd.github.everest-preview+json" \
            -u "${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}}" \
            --request POST \
            --data '{"event_type": "yak_release", "client_payload": { "text": "a title"}}' \
            https://api.github.com/repos/eb-rubenespinosa/brew_test/dispatches
