on:
  pull_request:
    branches:
      - master

name: Test semver validator
jobs:
  test_semver:
    runs-on: ubuntu-latest
    name: Test
    steps:
    - name: Validator
      uses: eb-rubenespinosa/semver-validation-action@0.0.4
      with:
        version: "1.1.1"
